before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
    - darwin
    - freebsd
    - linux
    - windows
    goarch:
    - '386'
    - amd64
    - arm
    - arm64

    ignore:
    - goarch: amd64
      goos: linux
    - goarch: arm
      goos: windows
    - goarch: arm64
      goos: freebsd
    - goarch: arm64
      goos: windows

release:
  prerelease: auto