on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  acceptance_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read go-version
        id: go-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.go-version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.content }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ github.event.inputs.terraformVersion }}
      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v${{ github.event.inputs.kindVersion }}
      - name: Run Acceptance Test Suite
        run: |
          make testacc