name: codecov
on:
  push:
    branches:
      - "main"

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true